backend:
  name: github
  repo: andreagzz11/devportfolio
media_folder: static/assets
public_folder: assets
collections:
  - name: chronicles
    label: Chronicles
    folder: chronicles
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: repo, label: Github Repo }
      - { name: demo, label: Live Demo }
      - { name: thumb, label: Thumbnail Image, widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: blog
    label: Blog
    folder: blogs
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: repo, label: Github Repo }
      - { name: demo, label: Live Demo }
      - { name: thumb, label: Thumbnail Image, widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: project
    label: Project
    folder: projects
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: repo, label: Github Repo }
      - { name: demo, label: Live Demo }
      - { name: thumb, label: Thumbnail Image, widget: image }
      - { name: body, label: Body, widget: markdown }
